# Generated by Django 2.2.2 on 2019-06-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articels',
            name='price',
            field=models.TextField(default=None),
        ),
    ]
