# Generated by Django 2.2.2 on 2019-06-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_articels_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articels',
            name='price',
        ),
    ]
